### ISSUE TITLE
Dead repo? Still maintained?

### ISSUE THREAD

**Issue by ronhanson** [bw2/ConfigArgParse#133]
Hi,
No commits have been made since quite long now. No pull requests accepted.
@bw2 - Do you still plan to maintain this project?
Do you need any help?
I can assist if needed.
Cheers,
Ronan

**Comment by ronhanson** [comment]
Thanks for the merges! 
Cool to see that the repo is still alive and bugfixed.
I will happily help you the best I can as a maintainer if needed.

**Comment by bw2** [comment]
Awesome!! Thanks! I just sent you an invite. 

If anyone else ( @hugovk ?)  is interested, please let me know.

**Comment by ronhanson** [comment]
Hi @bw2,
Sorry for not working more on issues related to this repo.
Apologies, I have a new position and I can't take assist anymore with this project. You can remove me from the maintainers if you'd like.
Wishing you the best, 
Ronan

**Comment by macfreek** [comment]
While I won't be able to help you as maintainer (sorry, I have some other older repositories I prefer to attend), I will try to do the following:

* Make a pull request for the code in #103 to improve parsing of argument keys and values (that I submitted in 2018; I was notified of this by a tag of my name in december, which is the only reason I had a look here).
  * This would add support for empty values (and would fix 2 issues)
  * This would add support for values that start with a hyphen (and would fix 3 issues)
* Try to improve some testing
  * For one, I will try make sure `tox` and `pytest` work. The later means that you can replace `python setup.py test` with `pytest` in `tox.ini` at some point in time (since it now complains that `python setup.py test` support will be removed in the future).

Thanks for making it available and maintaining it as much as possible.

**Comment by bw2** [comment]
Sounds great, thanks @macfreek

**Comment by macfreek** [comment]
I created three pull requests. #214 for making sure all tests are tip-top, and run without any warnings with either setuptools or pytest; #215 for specifying empty values, and quoted strings (including those that start with a dash, although that may have been fixed before); #216 for the ability to specify a counter value, like `verbose=3` in the config file.

These seem the most requested issues. Enjoy. I tried to be verbose in what I've done and why. Please tag me if you have any questions.

**Comment by bw2** [comment]
Awesome, thank you!
