### ISSUE TITLE
Python 2.6 support

### ISSUE THREAD

**Issue by kuba** [bw2/ConfigArgParse#17]
Would it be feasible to support Python 2.6 or is it a no go? Failing build log: https://travis-ci.org/letsencrypt/lets-encrypt-preview/jobs/60949344#L1366

Backref: https://github.com/letsencrypt/lets-encrypt-preview/pull/376

**Comment by kuba** [comment]
I've done some work at https://github.com/kuba/ConfigArgParse/commits/python2.6 (https://github.com/kuba/ConfigArgParse/commit/bf0e453804c6a9d79944c9420e166fd3adf472f8) and got it installable/importable. `argparse` PyPI package, however, doesn't seem to export `argparse.test` (https://code.google.com/p/argparse/source/browse/)...

**Comment by bw2** [comment]
On one hand, I'm somewhat reluctant to promise python2.6 support as a core feature since it might complicate future feature dev. On the other hand, it's neat that you were able to get it to work with so few changes. 
How would you feel about submitting a pull request and having python2.6 be unofficially supported for as long as it remains feasible to do so?

For argparse.tests, you might need to explicitly add them to your PYTHONPATH before running `python2.6 setup.py test`

**Comment by kuba** [comment]
I share your pain, we're facing the same python2.6 support problem over at letsencrypt. However, since the changes are straightforward (compat PR is really small), it should not take a lot of management burden. I would appreciate, though, if you could let us know when you are forced to stop that "semi-offical" support.

We are currently using black magic to get python2.6 compatible version (https://github.com/letsencrypt/lets-encrypt-preview/blob/master/requirements.txt#L2), so it would be great if you could upload a new version to PyPI once the PR is pulled in.

Thanks for help and for the awesome config/arg parsing library!
