### ISSUE TITLE
Refactor config file parsing, add support for more robust config file format(s)

### ISSUE THREAD

**Issue by bw2** [bw2/ConfigArgParse#21]
The current config file format is overly simplistic. Support for lists and booleans was added as an after-thought and works only for very simple use-cases, but doesn't generalize. 

This issue coalesces Issue #10 and other format-related Issues (#16, #19).

I think the right way to move forward on this will be:
- step 1 - refactor / extract out config file-format-aware code into a separate class that can be overriden more easily.
- step 2 - implement the class to provide a more robust alternative to the current format.

Any suggestions and/or pull requests will be appreciated.

**Comment by acx2015** [comment]
@bw2 FWIW, I have forked the repo and am actively working on adding support for [HOCON](https://github.com/chimpler/pyhocon).  I agree with you on the general plan--I will be abstracting out the file-format-aware code as part of my PR (although my priority is HOCON support because that's my main use case that isn't yet addressed).

**Comment by bw2** [comment]
I'm closing this and re-opening a new issue for creating a better config file format.
