### ISSUE TITLE
ConfigFileParse does not handle action='append'

### ISSUE THREAD

**Issue by russdill** [bw2/ConfigArgParse#39]
Only the last key/value pair in the file gets stored, eg:

--foo a --foo b --foo c

Will produce options.foo ['a', 'b', 'c']

But a file with:

foo = a
foo = b
foo = c

Will only produce ['c']

**Comment by ryran** [comment]
I'm not part of the project; just passing by ... but [the syntax is explained in the readme](https://github.com/bw2/ConfigArgParse#config-file-syntax).

Example:

```
foo = [a, b, c]
```

**Comment by ryran** [comment]
@bw2 would it be possible to allow the syntax @russdill was trying initially?

I ask because I hope that would fix an interoperability bug I'm facing when using configargparse + [argcomplete](https://github.com/kislyuk/argcomplete) -- tab-completion works great until I add a list directive to a config file (e.g., `foo = [a, b]`); then tab-completion completely fails.

**Comment by dwfreed** [comment]
That would add excessive complexity to the config file parser, which would have to know the actions of each arg in order to parse correctly.  Furthermore, this goes against the expected behavior of a config file: setting the same key twice should overwrite.  This is why the list syntax exists.

**Comment by jdelic** [comment]
> Furthermore, this goes against the expected behavior of a config file: setting the same key twice should overwrite. This is why the list syntax exists.

I don't disagree with that statement, but I want to chime in that then at least newlines inside the list syntax should be permitted. The way it is right now, it's hard to provide nicely formatted configuration files for users, since parameters with `action="append"` all **must** be specified on a single line. That leads to things like this:

```
# The following MUST be on one line:
pbuilder-opts=[--keyring /etc/apt/trusted.gpg, --debootstrapopts --keyring=/etc/apt/trusted.gpg, --mirror http://fileserver.maurusnet.test/debian]
```

It would be much nicer if we could do aligned config values:

```
pbuilder-opts=[--keyring /etc/apt/trusted.gpg, 
               --debootstrapopts --keyring=/etc/apt/trusted.gpg, 
               --mirror http://fileserver.maurusnet.test/debian]
```

Using quotes inside the list also leads to unexpected behavior, since 

```
pbuilder-opts=["--keyring /etc/apt/trusted.gpg", ...]
```

will lead to `ConfigArgParser.parse_args().pbuilder_opts = ['"--keyring /etc/apt/trusted.gpg"']` whereas

```python
import configargparse
parser = configargparse.ArgParser()
parser.add_argument("--pbuilder_opts", dest="pbuilder_opts", action="append")
print(parser.parse_args())
```

when invoked with `--pbuilder-opts="--keyring /etc/apt/trusted.gpg"` will result in `ConfigArgParser.parse_args().pbuilder_opts = ['--keyring /etc/apt/trusted.gpg']`, because Python's shell processing for `sys.argv` will unquote the argument value.

So I think that there is some middle ground to improve the config file parsing. The handling of quotes in lists might actually be considered a bug, right?

**Comment by dwfreed** [comment]
The config file parsing is so basic it's not even funny.  I'm tempted to make a pull request that just uses Python's ini parser.

**Comment by bw2** [comment]
@dwfreed a pull request that adds an  INIConfigFileParser(ConfigFileParser) would be appreciated.

**Comment by bw2** [comment]
Please reopen if this continues to be an issue.
