### ISSUE TITLE
Allow some command line options to be merged with those in the config

### ISSUE THREAD

**Issue by dufferzafar** [bw2/ConfigArgParse#50]
Taking from the first point of Features section of the readme:

> If a value is specified in more than one way then: command line > environment variables > config file values > defaults.

ConfigArgParse (CAP) overrides the values specified in the config file with those specified in the command line arguments. For most of the cases this behaviour is nice, except when it isn't.

Consider the case of a [mitmproxy user](https://github.com/mitmproxy/mitmproxy/issues/953) who has specified some scripts in the config file, and when they specify another script in the command line, the config ones get replaced.

The expected behaviour here is the merging of the list of scripts. 

I propose that CAP should add a new parameter (say `multiple`) to `parser.add_argument` that determines this override behaviour. So, for eg, the following snippet would result in an option that merges the values:

``` python
parser.add_argument(
    "-s", "--script", 
    action="append", type=str, dest="scripts" default=[],
    multiple="merge"
)
```

The `multiple` parameter could have values: 
- `merge` - Merge the values specified in the command line, env variables & config files & defaults.
- `override` - Follow the normal override process we follow now.

**Comment by dufferzafar** [comment]
If you feel that this feature makes sense for the library, I'd be happy to work on a pull :)

**Comment by bw2** [comment]
@dufferzafar thanks for offering. I don't think there's any issue with adding this.
Would this arg only be allowed for 'append' (and similar like nargs='*')? 
Also, I'd prefer a more specific key name in place of `multiple` - like `multisource` or even `multisource_behavior`

**Comment by dufferzafar** [comment]
Yeah, it makes sense to allow this only for `append` like args. 

I also agree that `multisource_behaviour` sounds like a much better name for the parameter.

So, do you have time to work on this, or would you like me to get started? :simple_smile:

**Comment by dwfreed** [comment]
I think you would also need to add a way to clear the current state in the case where the user wants to override and the application has suggested that they can be merged.  Creating a special arg called --clear-<arg>, where <arg> is the original arg less the leading --, would make this pretty simple, given the way that arguments are parsed.

**Comment by bw2** [comment]
@dufferzafar  I have no time to work on this, so if you want to tackle it, that would be great.
@dwfreed the multisource option behavior is kind of involved already, so I'd prefer to err on the side of a simpler (or at least simpler to describe) interface, and put aside the  --clear-<arg> flag until there's a strong use case for it.

**Comment by dwfreed** [comment]
I already have the code implemented, just cleaning up a few things, and will submit a pull request shortly, including the --clear- flag

**Comment by bw2** [comment]
@dwfreed thanks, and sorry, I'll take a look at your implementation, but am pretty sure I'm against adding the --clear- flag for now.

**Comment by dwfreed** [comment]
It's actually insanely simple, and takes advantage of how argparse parses arguments; it's just a regular argument, with action='store_const', dest=arg.dest, const=[].  It also has a special multisource setting, to bypass the already_in_command_line check, but skip the check that it have action='append'

**Comment by dwfreed** [comment]
(where arg is the original Action object for the arg that it's going to be clearing)

**Comment by bw2** [comment]
Though the implementation could be concise, I think few enough apps / users could ever need the --clear-<arg> that I don't think the added complexity in terms of the library's behavior is justified at this point + it would require users to read extra documentation, and could in principle break apps that have both an --arg and a --clear-arg explicitly defined.

**Comment by dwfreed** [comment]
Because it's a regular arg, the --clear-arg shows up in the help output just like everything else, and the help text for it is simple and concise.  Much more time will be spent on the documentation for the actual merge behavior, since the ConfigArgParse message about multiple locations is pretty clear that later locations override earlier locations.

In my opinion, if we're going to allow merging multiple locations, --clear-arg needs to be there.  Otherwise, how are you going to override a setting stored in a config file or environment variable that you don't want but have no way of changing directly?  For all other actions, later occurrences of an arg automatically override earlier ones in regular argparse, and only append merges, so everything else gets the behavior of --clear-arg for free.  Another example is having an alias that you commonly use, but want to override an append arg in the command line you actually use.

argparse does not allow actions with conflicting args, so if an app already has --clear-arg, and they try to add multisource_merge to --arg, argparse will throw an exception in the codepath handling the add_argument('--arg').  A quick inspection of my implementation would show that the developer could specify any value that evaluates to True except True itself, and --clear-arg will not be added.

Here's my implementation thus far:

https://github.com/dwfreed/ConfigArgParse/tree/multisource-merge

Todo list:
- [ ] Document the merge behavior
- [ ] Apply a sort to the environment variables so that usages of --clear-arg via environment variable actually work deterministically

Notes:

- I made it a boolean because I couldn't think of any other situations beside override (already the default) and merge that aren't too complex

**Comment by dwfreed** [comment]
Oh, another note: I've not written any tests for this yet, because I'm not familiar with the unittest framework.  If somebody knows how to write tests and wants to write the tests for this code, but doesn't know what to test (and don't just write tests for code coverage), I can help with that.

**Comment by bw2** [comment]
Not seeing any other requests for this, so closing this issue.

**Comment by andioz** [comment]
Hi, I would need this, as far as I can see it was never pulled in, right?
