### ISSUE TITLE
Value from env-var doesn't work for options defined on main parser when used with subparsers

### ISSUE THREAD

**Issue by itamaro** [bw2/ConfigArgParse#57]
Here's a minimal example:

```python

parser = configargparse.getArgumentParser()
parser.add('--foo', env_var='MY_FOO')
subparsers = parser.add_subparsers(help='Choose command')
sub_parser = subparsers.add_parser('sub')
args = parser.parse()
```

when running `MY_FOO=bar ./my_script.py` this works fine, but `MY_FOO=bar ./my_script.py sub` throws this errors:

`my_script.py: error: unrecognized arguments: --foo`

I assume this is because `--foo` is not an argument of the subparser, and this works by appending `--foo $MY_FOO` at the end of `sys.argv`...

**Comment by mtgrasse** [comment]
This behavior is because in parse_known_args() any argument sourced from the environment or config file is added to the *end* of the command line to be parsed.  Because of this arguments that should be passed to the top level parser are passed to the sub parsers

I was able to fix this for config files in my local copy by changing line 323 from:
args += config_args 
to:
args = config_args + args

Certainly a more sophisticated approach than the above is ultimately needed.  Could config files and environment variables be applied to sub parsers as well as the top level? If so, the approach of using the front of the list is just as bad as the end

**Comment by itamaro** [comment]
> Certainly a more sophisticated approach than the above is ultimately needed. Could config files and environment variables be applied to sub parsers as well as the top level? If so, the approach of using the front of the list is just as bad as the end

yes, the definitely can be applied to both, so another approach is needed...

maybe instead of adding them to the command line, they can be parsed separately, from the remaining (unparsed) args, after `parse_known_args`?

**Comment by bw2** [comment]
I couldn't reproduce this. 
```
parser = configargparse.getArgumentParser()
parser.add('--foo', env_var='MY_FOO')
subparsers = parser.add_subparsers(help='Choose command')
sub_parser = subparsers.add_parser('sub')
args = parser.parse()
print(args)
```

running `MY_FOO=bar ./my_script.py sub` 
prints Namespace(foo='bar')

Please reopen if you're still having this issue.

**Comment by nailgun** [comment]
I can confirm that it doesn't work in 0.13.0, but works in 0.12.0.
